# Generated by Django 3.1 on 2020-09-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200906_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.DeleteModel(
            name='MediaSection',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
