# Generated by Django 3.1 on 2020-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_imagesection_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesection',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
