# Generated by Django 3.1 on 2020-09-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200920_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.section')),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
            bases=('portfolio.section',),
        ),
    ]
