# Generated by Django 3.1 on 2020-09-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200921_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRenamedSection',
        ),
    ]
