# Generated by Django 3.1 on 2020-09-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200922_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSection',
        ),
    ]
