# Generated by Django 3.1 on 2020-09-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_cardsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsection',
            name='content',
        ),
        migrations.AddField(
            model_name='cardsection',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portfolio.image'),
            preserve_default=False,
        ),
    ]
