# Generated by Django 3.1 on 2020-09-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20200922_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardSection',
            new_name='ImageTextSection',
        ),
    ]
