# Generated by Django 3.1 on 2020-09-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20200922_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
