# Generated by Django 3.1 on 2020-09-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20200923_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.section')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image')),
            ],
            bases=('portfolio.section',),
        ),
    ]
