# Generated by Django 3.1 on 2020-10-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20200930_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_loc',
        ),
    ]
