# Generated by Django 3.1 on 2020-09-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.section')),
                ('content', models.TextField()),
            ],
            bases=('portfolio.section',),
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='mediasection',
            name='pathToMedia',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.page'),
        ),
    ]
