# Generated by Django 3.1 on 2020-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_imagesection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesection',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagesection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
