# Generated by Django 3.1 on 2020-09-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200917_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesection',
            name='content',
        ),
    ]
