# Generated by Django 3.1 on 2020-09-21 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0013_auto_20200921_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageSection',
            new_name='Image',
        ),
    ]
