# Generated by Django 3.1 on 2020-09-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_testrenamedsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextsection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.image'),
        ),
    ]
