# Generated by Django 3.1 on 2020-09-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_delete_cardsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.section')),
                ('content', models.TextField()),
            ],
            bases=('portfolio.section',),
        ),
    ]
