# Generated by Django 3.1 on 2020-09-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextsection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image'),
        ),
    ]
