# Generated by Django 3.1 on 2020-10-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_imagesection'),
        ('portfolio', '0026_auto_20200929_1907'),
    ]

    operations = [
    ]
