# Generated by Django 3.1 on 2020-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_imagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextsection',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
