# Generated by Django 3.1 on 2020-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20201001_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
