# Generated by Django 3.1 on 2020-10-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_merge_20201002_1838'),
        ('portfolio', '0029_auto_20201001_2204'),
    ]

    operations = [
    ]
