# Generated by Django 3.1 on 2020-10-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_merge_20201003_0022'),
        ('portfolio', '0030_portfolio_private'),
    ]

    operations = [
    ]
