# Generated by Django 3.1 on 2020-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_merge_20201016_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='background',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
