# Generated by Django 3.1 on 2020-10-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20201019_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsection',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
