# Generated by Django 3.1 on 2020-12-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_link_projectsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSection',
        ),
    ]
