# Generated by Django 3.1 on 2020-12-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_link_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagelink',
            old_name='link_id',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='pagelink',
            old_name='page_id',
            new_name='page',
        ),
    ]
