# Generated by Django 3.1 on 2020-12-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_auto_20201211_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='portfolio.page'),
        ),
    ]
