# Generated by Django 3.1 on 2020-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_auto_20201211_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('LinkedIn', 'Linkedin'), ('Github', 'Github'), ('Web', 'Web'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
