# Generated by Django 3.1 on 2020-12-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_auto_20201211_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionLink',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='portfolio.section')),
            ],
        ),
    ]
