# Generated by Django 3.1 on 2020-12-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_sectionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='orderNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.IntegerField(default=0),
        ),
    ]
