# Generated by Django 3.1 on 2020-12-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20201218_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='orderNumber',
        ),
    ]
