# Generated by Django 3.1 on 2020-12-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_auto_20201218_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='orderNumber',
            new_name='order_number',
        ),
    ]
