# Generated by Django 3.1 on 2020-12-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_auto_20201218_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='order_number',
            new_name='number',
        ),
    ]
