# Generated by Django 3.1 on 2020-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_auto_20201218_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['number']},
        ),
    ]
