# Generated by Django 3.1 on 2020-12-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_auto_20201218_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
