# Generated by Django 3.1 on 2020-12-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_auto_20201218_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.page'),
        ),
        migrations.AlterField(
            model_name='sectionlink',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.section'),
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.link')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.portfolio')),
            ],
        ),
    ]
