# Generated by Django 3.1 on 2020-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mediasection_page_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasection',
            name='section_ptr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='MediaSection',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
