# Check Dockerfile.backend for comments on the different Dockerfile commands
FROM node:alpine

RUN mkdir /frontend

WORKDIR /frontend

COPY ./src/frontend /frontend/

RUN npm install

CMD ["npm", "run", "start"]
