# Generated by Django 3.1 on 2020-10-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_mediasection_media'),
        ('account', '0002_auto_20200912_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio'),
        ),
    ]
