# Generated by Django 3.1 on 2020-08-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_Up',
            new_name='SignUp',
        ),
    ]
